openapi: 3.2.0
info:
  title: Clerk Frontend Account Portal API
  version: v1
  description: 'The Clerk REST Frontend API, meant to be accessed from a browser or native environment.


    This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.


    ### Versions


    When the API changes in a way that isn''t compatible with older versions, a new version is released.

    Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).


    ### Using the Try It Console


    The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme.

    To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.


    Please see https://clerk.com/docs for more information.'
  x-logo:
    url: https://clerk.com/_next/image?url=%2Fimages%2Fclerk-logo.svg&w=96&q=75
    altText: Clerk docs
    href: https://clerk.com/docs
  contact:
    email: support@clerk.com
    name: Clerk Team
    url: https://clerk.com/support
  termsOfService: https://clerk.com/terms
  license:
    name: MIT
    url: https://github.com/clerk/javascript/blob/main/LICENSE
servers:
- url: https://{domain}.clerk.accounts.dev
  variables:
    domain:
      default: example-destined-camel-13
      description: Your Development Instance Frontend API Domain.
security:
- {}
- DevBrowser: []
- ProductionBrowser: []
- ProductionNativeApp: []
  ProductionNativeFlag: []
tags:
- name: Account Portal
paths:
  /v1/account_portal:
    get:
      summary: Get Account Portal
      description: Get users account portal
      operationId: getAccountPortal
      responses:
        '200':
          $ref: '#/components/responses/Client.AccountPortal'
        '400':
          $ref: '#/components/responses/ClerkErrors'
        '401':
          $ref: '#/components/responses/ClerkErrors'
        '404':
          $ref: '#/components/responses/ClerkErrors'
      tags:
      - Account Portal
components:
  responses:
    ClerkErrors:
      description: Request was not successful
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ClerkErrors'
    Client.AccountPortal:
      description: Returns the account portal.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Client.AccountPortal'
  schemas:
    ClerkError:
      type: object
      properties:
        message:
          type: string
        long_message:
          type: string
        code:
          type: string
        meta:
          type: object
      required:
      - message
      - long_message
      - code
    ClerkErrors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ClerkError'
        meta:
          type: object
        clerk_trace_id:
          type: string
      required:
      - errors
    Client.AccountPortal:
      type: object
      additionalProperties: false
      properties:
        object:
          type: string
          enum:
          - account_portal
        allowed:
          type: boolean
        enabled:
          type: boolean
        internal_linking:
          type: boolean
        after_sign_in_url:
          type: string
        after_sign_up_url:
          type: string
        after_join_waitlist_url:
          type: string
        after_create_organization_url:
          type: string
        after_leave_organization_url:
          type: string
        logo_link_url:
          type: string
        customization:
          type: object
          properties:
            appearance:
              type:
              - string
              - 'null'
              enum:
              - auto
              - dark
              - light
            background_color_dark:
              type:
              - string
              - 'null'
            background_color_light:
              type:
              - string
              - 'null'
            primary_color_dark:
              type:
              - string
              - 'null'
            primary_color_light:
              type:
              - string
              - 'null'
          required:
          - appearance
          - background_color_dark
          - background_color_light
          - primary_color_dark
          - primary_color_light
      required:
      - object
      - allowed
      - enabled
      - internal_linking
      - after_sign_in_url
      - after_sign_up_url
      - after_join_waitlist_url
      - after_create_organization_url
      - after_leave_organization_url
      - logo_link_url
      - customization
  securitySchemes:
    ProductionBrowser:
      type: apiKey
      in: cookie
      name: __client
      description: 'The Client API token sent in the form of a browser cookie.


        Used to authenticate production browser applications.'
    DevBrowser:
      type: apiKey
      in: query
      name: __dev_session
      description: 'A Dev Browser API token sent as a query parameter.


        Used to authenticate only dev instances.


        To generate a dev instance API token you must first make a request to `/v1/dev_browser`

        and copy it from the response.'
    ProductionNativeApp:
      type: http
      scheme: bearer
      description: 'The Client API token sent in the `Authorization` header.


        Used to authenticate native applications.'
    ProductionNativeFlag:
      type: apiKey
      in: query
      name: _is_native
      description: 'If sent and the value is true, it instructs the server to parse the API token from the `Authorization` header.


        It should always be set to true when using the `Authorization` header authentication strategy.'
    ClientCredentials:
      type: http
      scheme: basic
      description: HTTP Basic Authentication using Client ID as username and Client Secret as password.
x-tagGroups:
- name: Environment
  tags:
  - Environment
- name: Client
  tags:
  - Client
  - Sessions
  - Sign Ins
  - Sign Ups
- name: User
  tags:
  - User
  - Active Sessions
  - Email Addresses
  - Phone Numbers
  - Web3 Wallets
  - Passkeys
  - External Accounts
  - TOTP
  - Backup Codes
  - Organizations Memberships
  - API Keys
- name: Organizations
  tags:
  - Organization
  - Organization Creation Defaults
  - Invitations
  - Membership Requests
  - Members
  - Domains
  - Roles
- name: Billing
  tags:
  - Plans
  - Subscriptions
  - Subscription Items
  - Checkouts
  - Payment Methods
  - Statements
  - Payment Attempts
- name: Other
  tags:
  - Well Known
  - DevBrowser
  - DevTools
  - Health
  - OAuth2 Identity Provider
  - OAuth2 Callbacks
  - SAML
  - Waitlist
  - Enterprise Connections
