naftiko: 1.0.0-alpha2
info:
  label: Clerk Backend Api — Instance Settings
  description: 'Clerk Instance Settings capability. 11 operations. Lead operation: Fetch the Current Instance.'
  tags:
  - Clerk
  - Instance Settings
  created: '2026-05-22'
  modified: '2026-05-22'
binds:
- namespace: env
  keys:
    CLERK_SECRET_KEY: CLERK_SECRET_KEY
capability:
  consumes:
  - type: http
    namespace: clerk-backend-api-instance-settings
    baseUri: https://api.clerk.com/v1
    description: Clerk clerk-backend-api Instance Settings business capability.
    resources:
    - name: instance
      path: /instance
      operations:
      - name: GetInstance
        method: GET
        description: Fetch the Current Instance
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
      - name: UpdateInstance
        method: PATCH
        description: Update Instance Settings
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: instance-restrictions
      path: /instance/restrictions
      operations:
      - name: UpdateInstanceRestrictions
        method: PATCH
        description: Update Instance Restrictions
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: instance-protect
      path: /instance/protect
      operations:
      - name: GetInstanceProtect
        method: GET
        description: Get Instance Protect Settings
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
      - name: UpdateInstanceProtect
        method: PATCH
        description: Update Instance Protect Settings
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: instance-communication
      path: /instance/communication
      operations:
      - name: GetInstanceCommunication
        method: GET
        description: Get Instance Communication Settings
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
      - name: UpdateInstanceCommunication
        method: PATCH
        description: Update Instance Communication Settings
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: instance-oauth-application-settings
      path: /instance/oauth_application_settings
      operations:
      - name: GetInstanceOAuthApplicationSettings
        method: GET
        description: Get OAuth Application Settings
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
      - name: UpdateInstanceOAuthApplicationSettings
        method: PATCH
        description: Update OAuth Application Settings
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
    - name: instance-organization-settings
      path: /instance/organization_settings
      operations:
      - name: GetInstanceOrganizationSettings
        method: GET
        description: Get Instance Organization Settings
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
      - name: UpdateInstanceOrganizationSettings
        method: PATCH
        description: Update Instance Organization Settings
        outputRawFormat: json
        outputParameters:
        - name: result
          type: object
          value: $.
        inputParameters:
        - name: body
          in: body
          type: object
          description: Request body (JSON).
          required: true
